backend:
  name: git-gateway
  branch: main

# 圖片存放位置 - 對應你的 assets 結構
media_folder: "assets/images"
public_folder: "/assets/images"

# 內容管理集合
collections:
  # 首頁內容管理
  - name: "homepage"
    label: "首頁內容"
    files:
      # 主視覺橫幅
      - label: "主視覺橫幅"
        name: "hero"
        file: "data/hero.json"
        fields:
          - {label: "主標題", name: "title", widget: "string", default: "一條龍專業服務\n讓您安心成家置產"}
          - {label: "副標題", name: "subtitle", widget: "string", default: "15年在地深耕，值得信賴的不動產夥伴"}
          - {label: "認證標章", name: "badge", widget: "string", default: "內政部營建署社會住宅包租代管 合法第四期廠商"}
          - {label: "主要按鈕文字", name: "primaryButton", widget: "string", default: "立即諮詢"}
          - {label: "次要按鈕文字", name: "secondaryButton", widget: "string", default: "了解更多"}

      # 聯絡資訊
      - label: "聯絡資訊"
        name: "contact"
        file: "data/contact.json"
        fields:
          - {label: "服務電話", name: "phone", widget: "string", default: "02-2998-9596"}
          - {label: "房客LINE", name: "tenantLine", widget: "string", default: "https://lin.ee/izjYq9H"}
          - {label: "房東LINE", name: "landlordLine", widget: "string", default: "https://lin.ee/elZYPEn"}
          - {label: "公司地址", name: "address", widget: "string", default: "24251新北市新莊區昌平街84號4樓"}
          - {label: "營業時間", name: "hours", widget: "string", default: "週一至週六 9:00-18:00"}
          - {label: "電子信箱", name: "email", widget: "string", default: "aaa95969596@gmail.com"}

  # 服務項目管理
  - name: "services"
    label: "服務項目"
    folder: "data/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "服務名稱", name: "title", widget: "string"}
      - {label: "圖標代碼", name: "icon", widget: "string", hint: "例如：bi-buildings"}
      - {label: "簡短描述", name: "description", widget: "text"}
      - {label: "是否推薦", name: "featured", widget: "boolean", default: false}
      - {label: "排序", name: "order", widget: "number", default: 1}

  # 最新消息管理
  - name: "news"
    label: "最新消息"
    folder: "data/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "分類", name: "category", widget: "select", options: ["政策", "熱門", "最新", "公司動態"]}
      - {label: "圖標", name: "icon", widget: "string", default: "bi-newspaper"}
      - {label: "摘要", name: "excerpt", widget: "text"}
      - {label: "內容", name: "content", widget: "markdown"}

# 中文介面
locale: 'zh-Hant'

# 編輯工作流程
publish_mode: editorial_workflow

# 顯示預覽
show_preview_links: true
